repos:
  - repo: local
    hooks:
      - id: swiftlint-format
        name: swiftlint-format
        entry: bash ci_scripts/tasks/format_swift.sh
        language: system
        types: [swift]
        pass_filenames: false
      - id: swiftlint-strict
        name: swiftlint-strict
        entry: bash ci_scripts/tasks/lint_swift.sh
        language: system
        types: [swift]
        pass_filenames: false
